version: "3.9"

services:
  db:
    image: postgres:15
    container_name: warehouse_db
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
      POSTGRES_DB: warehouse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always

  web:
    build: .
    container_name: warehouse_app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql+psycopg2://warehouse_user:warehouse_pass@db:5432/warehouse_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: